language: php

php:
  - 5.3
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover